import { NgFor, NgIf } from '@angular/common';
import { Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { CartService } from '../../core/services/cart.service';
import { CartSummaryComponent } from '../../shared/components/cart-summary.component';
import { EmptyStateComponent } from '../../shared/components/empty-state.component';

@Component({standalone:true,imports:[ReactiveFormsModule,NgIf,NgFor,CartSummaryComponent,EmptyStateComponent],template:`<h1>Checkout</h1><ng-container *ngIf="cart.items().length; else empty"><form [formGroup]="form" (ngSubmit)="submit()"><input placeholder="Nombre" formControlName="customerName" /><input placeholder="Teléfono" formControlName="phone" /><input placeholder="Email" formControlName="email" /><input placeholder="Dirección" formControlName="address" /><input placeholder="Ciudad" formControlName="city" /><label>Método de pago<select formControlName="paymentMethod"><option>Efectivo</option><option>Transferencia</option><option>Tarjeta dummy</option></select></label><label>Entrega<select formControlName="deliveryMethod"><option>Recoger en sucursal</option><option>Entrega local</option></select></label><button [disabled]="form.invalid || loading">{{loading?'Procesando...':'Confirmar pedido'}}</button></form><app-cart-summary [subtotal]="cart.subtotal()" [shipping]="cart.shipping()" [total]="cart.total()"></app-cart-summary><div *ngIf="success">Pedido confirmado ✅</div></ng-container><ng-template #empty><app-empty-state title="No hay productos" message="Tu carrito está vacío."></app-empty-state></ng-template>`})
export class CheckoutPage{ readonly cart=inject(CartService); private readonly fb=inject(FormBuilder); loading=false; success=false; readonly form=this.fb.nonNullable.group({customerName:['',Validators.required],phone:['',Validators.required],email:['',[Validators.required,Validators.email]],address:['',Validators.required],city:['',Validators.required],paymentMethod:['Efectivo',Validators.required],deliveryMethod:['Recoger en sucursal',Validators.required]}); submit(){if(this.form.invalid)return; this.loading=true; setTimeout(()=>{this.success=true; this.loading=false; this.cart.clearCart(); this.form.reset({customerName:'',phone:'',email:'',address:'',city:'',paymentMethod:'Efectivo',deliveryMethod:'Recoger en sucursal'});},700);} }
