import { CommonModule } from '@angular/common';
import { Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { BarbersDataService } from '../../core/services/barbers-data.service';
import { BookingService } from '../../core/services/booking.service';
import { ServicesDataService } from '../../core/services/services-data.service';

@Component({standalone:true,imports:[CommonModule,ReactiveFormsModule],template:`<h1>Reservar cita</h1><form [formGroup]="form" (ngSubmit)="submit()"><label>Nombre<input formControlName="customerName" /></label><small *ngIf="form.controls.customerName.touched&&form.controls.customerName.invalid">Ingresa tu nombre.</small><label>Teléfono<input formControlName="phone" /></label><label>Email<input formControlName="email" /></label><label>Servicio<select formControlName="serviceId"><option value="">Selecciona</option><option *ngFor="let s of services" [value]="s.id">{{s.name}}</option></select></label><label>Barbero<select formControlName="barberId"><option value="">Selecciona</option><option *ngFor="let b of barbers" [value]="b.id">{{b.name}}</option></select></label><label>Fecha<input type="date" formControlName="date" /></label><label>Hora<input type="time" formControlName="time" /></label><label>Notas<textarea formControlName="notes"></textarea></label><button [disabled]="form.invalid || loading">{{loading?'Guardando...':'Confirmar reserva'}}</button></form><div *ngIf="folio" class="success">Reserva confirmada. Tu folio es <strong>{{folio}}</strong>.</div>` ,styles:[`form{display:grid;gap:.7rem;max-width:640px}input,select,textarea,button{padding:.7rem;border-radius:8px;border:1px solid #333;background:#151515;color:#f6f1e9}.success{margin-top:1rem;padding:1rem;border:1px solid #2f6f45;background:#153624}`]})
export class BookingPage{ private readonly fb=inject(FormBuilder); private readonly booking=inject(BookingService); private readonly servicesData=inject(ServicesDataService); private readonly barbersData=inject(BarbersDataService); loading=false; folio=''; readonly services=this.servicesData.getAll(); readonly barbers=this.barbersData.getAvailable(); readonly form=this.fb.nonNullable.group({customerName:['',[Validators.required,Validators.minLength(3)]],phone:['',[Validators.required,Validators.minLength(10)]],email:[''],serviceId:['',Validators.required],barberId:['',Validators.required],date:['',Validators.required],time:['',Validators.required],notes:['']}); submit(){if(this.form.invalid){this.form.markAllAsTouched();return;} this.loading=true; setTimeout(()=>{this.folio=this.booking.createBooking(this.form.getRawValue()); this.form.reset({customerName:'',phone:'',email:'',serviceId:'',barberId:'',date:'',time:'',notes:''}); this.loading=false;},600);} }
